# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 188a646ae012110ea40fa25c87f303d62fbfb335b33d61706e23996995ec888855ec49d2a1286181241fe4743bf429ca60e160ff83260bdc155fd845dd2cf2da

test:
  secret_key_base: 6c4664e589569c191d0460cc2652a2110bdaeded3a5d5d2983ebabdc5ff4005781c8ee5c112f02305f0c368f4aaebff67d3922941f9140f01d10b492363f0794

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
